name: CI

on:
  push:
    branches: [ "setup-actions" ]
  pull_request:
    branches: [ "setup-actions" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: install xcas
        run: |
          sudo apt-get update
          sudo apt-get install -y xcas

      - name: run master
        run: |
          result=$(icas master 2>/dev/null | tail -n1)
          if [[ "$result" == *false* ]]; then
            echo $result
            exit 1
          else
            echo "pass"
          fi
